/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ci.test;

public class App {
    // public String getGreeting() {
    //     // some comments
    //     return "Hello World !";
    // }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
